PROGRAM pre10_2
IMPLICIT NONE
INTEGER, PARAMETER :: MAX = 10
INTEGER :: i
REAL, DIMENSION(MAX) :: a = (/(REAL(i*2), i=1,10)/)
REAL, DIMENSION(MAX/2) :: b
b = Log(a(4:8))
WRITE(*,*) b(3:4)
END PROGRAM pre10_2